### ISSUE TITLE
vps-bandwagonhost部署的谷歌不定期报错重启apache2会恢复

### ISSUE THREAD

**Issue by hnuzhoulin** [aploium/zmirror#39]
我在另一个vps的就不会，已经更新到最新版，但是还是不定期的出现下面的额错误，重启apache2后又会恢复正常。

apache2日志如下：

```
[Mon Nov 07 22:19:37.455355 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 109.190.102.122:8740]     response = self.make_response(rv)
[Mon Nov 07 22:19:37.455361 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 109.190.102.122:8740]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1731, in make_response
[Mon Nov 07 22:19:37.455367 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 109.190.102.122:8740]     raise ValueError('View function did not return a response')
[Mon Nov 07 22:19:37.455390 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 109.190.102.122:8740] ValueError: View function did not return a response
[Mon Nov 07 22:19:37.455420 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 109.190.102.122:8740]
[Mon Nov 07 22:25:25.637749 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996] [2016-11-07 22:25:25,637] ERROR in app: Exception on /ip_ban_verify_page [HEAD]
[Mon Nov 07 22:25:25.637789 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996] Traceback (most recent call last):
[Mon Nov 07 22:25:25.637795 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1988, in wsgi_app
[Mon Nov 07 22:25:25.637799 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996]     response = self.full_dispatch_request()
[Mon Nov 07 22:25:25.637804 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1642, in full_dispatch_
request
[Mon Nov 07 22:25:25.637808 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996]     response = self.make_response(rv)
[Mon Nov 07 22:25:25.637812 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996]   File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1731, in make_response
[Mon Nov 07 22:25:25.637817 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996]     raise ValueError('View function did not return a response')
[Mon Nov 07 22:25:25.637823 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996] ValueError: View function did not return a response
[Mon Nov 07 22:25:25.637843 2016] [wsgi:error] [pid 17190:tid 140445830973184] [remote 139.129.217.191:8996]
[Mon Nov 07 22:29:41.957462 2016] [wsgi:error] [pid 17190:tid 140445663115008] [22:29:41] [INFO] CronTask: cache_clean_soft Target: <function cache_clean at 0x7fbc0ea0bb70>
[Mon Nov 07 22:29:41.957529 2016] [wsgi:error] [pid 17190:tid 140445663115008]
[Mon Nov 07 22:44:42.058541 2016] [wsgi:error] [pid 17190:tid 140445663115008] [22:44:42] [INFO] CronTask: cache_clean_soft Target: <function cache_clean at 0x7fbc0ea0bb70>
[Mon Nov 07 22:44:42.058601 2016] [wsgi:error] [pid 17190:tid 140445663115008]
[Mon Nov 07 22:59:42.158404 2016] [wsgi:error] [pid 17190:tid 140445663115008] [22:59:42] [INFO] CronTask: cache_clean_soft Target: <function cache_clean at 0x7fbc0ea0bb70>
[Mon Nov 07 22:59:42.158482 2016] [wsgi:error] [pid 17190:tid 140445663115008]
[Mon Nov 07 23:14:42.258899 2016] [wsgi:error] [pid 17190:tid 140445663115008] [23:14:42] [INFO] CronTask: cache_clean_soft Target: <function cache_clean at 0x7fbc0ea0bb70>
[Mon Nov 07 23:14:42.258965 2016] [wsgi:error] [pid 17190:tid 140445663115008]
[Mon Nov 07 23:29:42.359301 2016] [wsgi:error] [pid 17190:tid 140445663115008] [23:29:42] [INFO] CronTask: cache_clean_soft Target: <function cache_clean at 0x7fbc0ea0bb70>
[Mon Nov 07 23:29:42.359357 2016] [wsgi:error] [pid 17190:tid 140445663115008]
[Mon Nov 07 23:44:42.459341 2016] [wsgi:error] [pid 17190:tid 140445663115008] [23:44:42] [INFO] CronTask: cache_clean_soft Target: <function cache_clean at 0x7fbc0ea0bb70>
[Mon Nov 07 23:44:42.459413 2016] [wsgi:error] [pid 17190:tid 140445663115008]
[Mon Nov 07 23:59:42.559557 2016] [wsgi:error] [pid 17190:tid 140445663115008] [23:59:42] [INFO] CronTask: cache_clean_soft Target: <function cache_clean at 0x7fbc0ea0bb70>
[Mon Nov 07 23:59:42.559633 2016] [wsgi:error] [pid 17190:tid 140445663115008]
[Tue Nov 08 00:14:42.659405 2016] [wsgi:error] [pid 17190:tid 140445663115008] [00:14:42] [INFO] CronTask: cache_clean_soft Target: <function cache_clean at 0x7fbc0ea0bb70>
[Tue Nov 08 00:14:42.659461 2016] [wsgi:error] [pid 17190:tid 140445663115008]
[Tue Nov 08 00:29:42.759402 2016] [wsgi:error] [pid 17190:tid 140445663115008] [00:29:42] [INFO] CronTask: cache_clean_soft Target: <function cache_clean at 0x7fbc0ea0bb70>
[Tue Nov 08 00:29:42.759487 2016] [wsgi:error] [pid 17190:tid 140445663115008]

```

**Comment by zhenhappy** [comment]
我已经设置计划任务每个小时重启apache
