### ISSUE TITLE
external_domains 问题？

### ISSUE THREAD

**Issue by ttestdock** [aploium/zmirror#46]
google镜像中external_domains 添加www.toptenreviews.com & www.economist.com，总是出现zmirror internal error.（openshift平台 python 3.3）

Detail
Attrib	Value
cache_control	None
cacheable	False
client_header	{'connection': 'Keep-Alive', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'x-forwarded-for': '', 'x-forwarded-proto': 'https', 'x-client-ip': '', 'accept-language': 'en-US,en;q=0.8,zh-CN;q=0.5,zh;q=0.3', 'x-forwarded-ssl-client-cert': '', 'x-forwarded-port': '443', 'x-forwarded-host': 'www.google.com', 'referer': 'https://', 'x-forwarded-server': 'www.google.com', 'x-request-start': 't=1480296314766230', 'accept-encoding': 'gzip, deflate'}
content_type	None
dump	<bound method ZmirrorThreadLocal.dump of <zmirror.threadlocal.ZmirrorThreadLocal object at 0x7fe7a19fa390>>
extra_cookies	{}
extra_resp_headers	{}
init	<bound method ZmirrorThreadLocal.init of <zmirror.threadlocal.ZmirrorThreadLocal object at 0x7fe7a19fa390>>
is_external_domain	True
is_https	True
method	GET
mime	None
remote_domain	www.toptenreviews.com
remote_path	/
remote_path_query	/
remote_response	None
remote_url	https://www.toptenreviews.com/
request_data	
request_data_encoded	b''
request_data_encoding	utf-8
set_cookies	<bound method ZmirrorThreadLocal.set_cookies of <zmirror.threadlocal.ZmirrorThreadLocal object at 0x7fe7a19fa390>>
set_extra_resp_header	<bound method ZmirrorThreadLocal.set_extra_resp_header of <zmirror.threadlocal.ZmirrorThreadLocal object at 0x7fe7a19fa390>>
streamed_our_response	False
temporary_domain_alias	[]
time	{'start_time': 1.11560118, 'req_start_time': 1480296314.776441}
url_no_scheme	www.toptenreviews.com/
Additional Information

Unknown Error

Traceback

Traceback (most recent call last):
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/packages/urllib3/connection.py", line 339, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/packages/urllib3/connection.py", line 349, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py", line 150, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
requests.packages.urllib3.packages.ssl_match_hostname._implementation.CertificateError: hostname 'www.toptenreviews.com' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 624, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: hostname 'www.toptenreviews.com' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/app-root/runtime/repo/zmirror/zmirror.py", line 2405, in zmirror_enter
    resp = main_function(input_path=input_path)
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/app-root/runtime/repo/zmirror/zmirror.py", line 2481, in main_function
    request_remote_site()
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/app-root/runtime/repo/zmirror/zmirror.py", line 2012, in request_remote_site
    data=parse.request_data_encoded,
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/app-root/runtime/repo/zmirror/zmirror.py", line 1773, in send_request
    verify=not developer_do_not_verify_ssl,
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/openshift/5833bfe789f5cfe6e200014b/python/virtenv/venv/lib/python3.3/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'www.toptenreviews.com' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'

**Comment by aploium** [comment]
很抱歉...zmirror不支持py3.3, 仅支持3.4+
openshift上目前来看是无法部署的
