### ISSUE TITLE
运行 wsgi.py报错，找不到config

### ISSUE THREAD

**Issue by ttestdock** [aploium/zmirror#63]
Traceback (most recent call last):
  File "wsgi.py", line 9, in <module>
    from zmirror.zmirror import app as application
  File "/app/zmirror/zmirror.py", line 78, in <module>
    from config import *
ImportError: No module named 'config'

**Comment by Alife** [comment]
see https://github.com/aploium/zmirror/tree/master/more_configs

**Comment by ttestdock** [comment]
@Alife heroku platform，PY 3.5.1
重命名了，还是找不到config
