### ISSUE TITLE
直接运行时Port80被占用/同VPS多域名部署

### ISSUE THREAD

**Issue by ClarkeCheng** [aploium/zmirror#7]
root@a:~/zmirror# python3 wsgi.py
[16:36:07] [INFO] zmirror version:  0.23.1-dev from Aploium <i@z.codes>
[16:36:07] [INFO] Github: https://github.com/Aploium/zmirror
[16:36:07] [INFO] config file found
[16:36:07] [INFO] Local file cache enabled
Traceback (most recent call last):
  File "wsgi.py", line 24, in <module>
    host='0.0.0.0',  # \u9ed8\u8ba4\u53ea\u5141\u8bb8\u672c\u673a\u8bbf\u95ee, \u5982\u679c\u4f60\u5e0c\u671b\u8ba9\u5916\u7f51\u8bbf\u95ee, \u8bf7\u53bb\u6389\u672c\u884c\u7684\u6ce8\u91ca
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 656, in inner
    fd=fd)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python3.4/socketserver.py", line 429, in __init__
    self.server_bind()
  File "/usr/lib/python3.4/http/server.py", line 133, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.4/socketserver.py", line 440, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
root@a:~/zmirror#

**Comment by aploium** [comment]
因为你本机的80端口被其他程序占用了
你可以查看一下是哪个程序占用了80端口
然后关掉它

**Comment by ClarkeCheng** [comment]
嗯，如果我在同一台VPS上同时开Google、Twitter、Youtube等的镜像，是不是都要给它们设置不同的端口？

**Comment by aploium** [comment]
如果你使用Apache的话(比如根据[教程](https://github.com/aploium/zmirror/wiki/%E9%83%A8%E7%BD%B2%E6%94%AF%E6%8C%81HTTPS%E5%92%8CHTTP2.0%E7%9A%84%E9%95%9C%E5%83%8F)部署), 就不需要多个端口

使用Apache的visual host功能, 可以把几个域名绑定到同一个IP同一个端口上
比如说zmirrordemo.com里面的几个镜像, 就是同一台VPS同一个端口, 但是不同域名

具体做法是把 `/etc/apache2/sites-enabled` 里的已有镜像的Apache配置文件复制一份, zmirror程序文件夹也复制一份, 新的Apache配置文件对应新的zmirror程序文件夹(以及新的域名)
Apache会自动根据请求的域名， 来调用域名对应的镜像程序

当然, 如果你只有一个域名, 那么只能是不同端口
如果你有多个域名, 那么可以同一个端口, 通过域名来区分各个镜像

**Comment by aploium** [comment]
已加入端口被占用时的友好的提示, 本issue关闭
对于同VPS多域名, 请新开一个issue
