### ISSUE TITLE
手动部署的一个小BUG

### ISSUE THREAD

**Issue by rocklinsuv** [aploium/zmirror#81]
Vultr VPS LA $5+Ubuntu 16.04
测试手动部署（一键部署已经满足不了我看AV的心）
按教程部署完毕，遇到internal  error。回看error log发现：

File "/var/www/google/wsgi.py", line 9, in <module>
from zmirror.zmirror import app as application
File "/var/www/google/zmirror/zmirror.py", line 23, in <module>
from flask import Flask, request, make_response, Response, redirect
ImportError: No module named 'flask'
mod_wsgi (pid=32603): Target WSGI script '/var/www/google/wsgi.py' cannot be loaded as Python module.

重新sudo python3 -m pip install flask 发现error：
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'

最后用sudo apt-get install python3-setuptools 解决问题
不知道是不是VPS自带Ubuntu的原因，反正是重新安装纯净系统后马上部署zmirror遇到的

**Comment by rocklinsuv** [comment]
补充一下：某艾薇网站成功被我反代，但是视频看不了，因为点开视频需要运行一个insecure的javascript，然后从源网站获取视频。
跪求解决方法与思路，蟹蟹
